version: 2

references:

base_image: &base_image
  hashicorp/terraform:0.11.13

working_directory: &working_directory
  ~/tf_run

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory
  environment:
    BASH_ENV: /root/.bashrc

repo_cache_key: &repo_cache_key
  v1-repo-{{ .Branch }}-{{ .Revision }}

# Step to restore repository from cache
restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      pwd
      ls -la
      cd ./accounts/fitzroy
      terraform init
      cd ../accounts/subaccounts/sandbox
      terraform init
apply_job: &apply_job
  <<: *default_config
  steps:
    - *restore_repo
    - *terraform_init
    - attach_workspace:
        at: *working_directory
    - run:
        name: terraform apply
        command: |
          pwd
          ls -la
          cd ./accounts/fitzroy
          terraform apply --auto-approve ./terraform.plan
          cd ../accounts/subaccounts/sandbox
          terraform apply --auto-approve ./terraform.plan
jobs:
  build:
    <<: *default_config
    steps:
      - checkout
  #     - run:
  #         name: terraform fmt
  #         command: |
  #           cd ./accounts
  #           if [ $(terraform fmt | grep -v .terraform | tee fmt_result.txt | wc -l) -gt 0 ]; then
  #             echo "Format of this terraform files is not appropiate:"
  #             echo
  #             cat fmt_result.txt
  #             rm fmt_result.txt
  #             git checkout -- .
  #             echo
  #             echo "Please run terraform fmt"
  #             exit 1
  #           fi
      - *save_repo

  plan:
    <<: *default_config
    steps:
      - *restore_repo
      - *terraform_init
      - run:
          name: terraform plan
          command: |
            pwd
            ls -la
            source $BASH_ENV
            cd ./accounts/fitzroy
            terraform plan -out=./terraform.plan
            cd ../accounts/subaccounts/sandbox
            terraform plan -out=./terraform.plan
            popd
      - persist_to_workspace:
          root: *working_directory
          paths:
            - ./accounts/fitzroy/terraform.plan
            - ./accounts/subaccounts/*/terraform.plan

  apply:
    <<: *apply_job
  apply-with-approval:
    <<: *apply_job

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan
      - approve:
          type: approval
          requires:
            - plan
          filters:
            branches:
              only: master
      - apply-with-approval:
          requires:
            - approve
          filters:
            branches:
              only: master
      - apply:
          requires:
            - plan
          filters:
            branches:
              only: staging

