version: 2.1

orbs:
  slack: circleci/slack@3.2.0

references:

base_image: &base_image
  hashicorp/terraform:0.11.13

working_directory: &working_directory
  ~/tf_run

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory

repo_cache_key: &repo_cache_key
  v1-repo-{{ .Branch }}-{{ .Revision }}

# Step to restore repository from cache
restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      cd ./accounts/fitzroy
      terraform init
      cd ../subaccounts/sandbox
      terraform init

apply_job: &apply_job
  <<: *default_config
  steps:
    - *restore_repo
    - *terraform_init
    - attach_workspace:
        at: *working_directory
    - run:
        name: terraform apply
        command: |
          cd ./accounts/fitzroy
          terraform apply --auto-approve ./terraform.plan
          cd ../subaccounts/sandbox
          terraform apply --auto-approve ./terraform.plan
jobs:
  plan:
    <<: *default_config
    steps:
      - checkout
      - *save_repo
      - *terraform_init
      - run:
          name: terraform plan
          command: |
            cd ./accounts/fitzroy
            terraform plan -out=./terraform.plan
            cd ../subaccounts/sandbox
            terraform plan -out=./terraform.plan
      - persist_to_workspace:
          root: *working_directory
          paths:
            - ./accounts/*


  apply:
    <<: *apply_job
  apply-with-approval:
    <<: *apply_job

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan:
          context: fitzroy-terraform
      - slack:
          message: Terraform apply is pending approval.
      - approve:
          type: approval
          requires:
            - plan
          filters:
            branches:
              only: master
      - apply-with-approval:
          context: fitzroy-terraform
          requires:
            - approve
          filters:
            branches:
              only: master
      # - apply:
      #     context: fitzroy-terraform
      #     requires:
      #       - plan
      #     filters:
      #       branches:
      #         only: staging

